### ISSUE TITLE
Standardization of modules

### ISSUE THREAD

**Issue by josephcslater** [vibrationtoolbox/vibration_toolbox#25]
I'd like to standardize on using sp in place of np as it's simpler and more consistent for users if they can use fewer calls in general. np ends up looking like a subset of sp in the way sp has evolved. 

These changes include all modules and notebooks here.

**Comment by raphaeltimbo** [comment]
I have changed to call numpy as np based on the following recommendations from https://docs.scipy.org/doc/scipy/reference/api.html -

>  Guidelines for importing functions from Scipy: "The scipy namespace itself only contains functions imported from numpy. These functions still exist for backwards compatibility, but should be imported from numpy directly."

I normally only import some modules from scipy (e.g. scipy.signal..).

**Comment by josephcslater** [comment]
Agreed (although my habits will die slowly).
