### ISSUE TITLE
Vib should be Vibe in methods, classes, names, documents

### ISSUE THREAD

**Issue by josephcslater** [vibrationtoolbox/vibration_toolbox#26]
Consistent typo error that will break code. Needs edits throughout.

**Comment by raphaeltimbo** [comment]
Did the refactoring with the following commits:
31eed92 360038b 3365603 

Next time I will try to put everything in a single pull request instead of pushing the commits directly. I think this may help keeping things organized and it will be easier to refer to.

**Comment by josephcslater** [comment]
You are more organized than me.

**Comment by josephcslater** [comment]
It took longer for me to hit "close issue" than to have it addressed.  Neat.
