### ISSUE TITLE
Jupyter Notebooks

### ISSUE THREAD

**Issue by josephcslater** [vibrationtoolbox/vibration_toolbox#37]
We need to figure out how the notebooks we use in the documentation can easily be accessed in whole and downloaded by users from within the online documentation. I've seen this capability elsewhere in other packages using sphinx and jupyter, but cannot recall where.

**Comment by raphaeltimbo** [comment]
I think this is solved now. 
See #51 and #52 .
I have already updated the web page and things seem to working.

**Comment by raphaeltimbo** [comment]
I am closing this one based on #53 .
If necessary we can reopen it latter.
