### ISSUE TITLE
Any of you had problems running doctests.py on spyder?

### ISSUE THREAD

**Issue by AnushaAnisetti** [vibrationtoolbox/vibration_toolbox#38]
![image](https://cloud.githubusercontent.com/assets/14098051/25808597/395a6c74-3428-11e7-841c-eaa89da4424c.png)

  File "C:\Users\Admin\Anaconda3\lib\doctest.py", line 357, in __init__
    pdb.Pdb.__init__(self, stdout=out, nosigint=True)

TypeError: __init__() got an unexpected keyword argument 'nosigint'

while I run .py files on spyder. I looked into it online and one of the solutions is to edit pdb.py. Here is the link-
http://stackoverflow.com/questions/37669435/python-3-5-typeerror-init-got-an-unexpected-keyword-argument-nosigint

**Comment by josephcslater** [comment]
I'm not doing it in spyder. I'm running pytest from the command prompt.

**Comment by raphaeltimbo** [comment]
Tests are now covered in https://github.com/vibrationtoolbox/vibration_toolbox/blob/master/CONTRIBUTING.rst
I think we can close this issue.
