### ISSUE TITLE
Notebooks organization

### ISSUE THREAD

**Issue by raphaeltimbo** [vibrationtoolbox/vibration_toolbox#49]
I was thinking that we could organize the notebooks in the following way (I am thinking here based on what I have seen in other projects)

We would have the notebooks in two different places:

- Tutorials : here we would have one specific notebook for each module (sdof, mdof, ema etc.) The purpose of these notebooks would be to go through the modules functionalities. 

- Gallery (or something like that) : Here we would have any kind of notebook that uses the toolbox to explore some vibration aspect, interest thing etc. The beat phenomenon notebook for example would go here.

What do you think?

**Comment by josephcslater** [comment]
I don't have anything better. I like the idea of having them be "common", but have no solution better than what I did before. 

Tutorials would be "just for documenting" while the gallery could be linked to with html links and perhaps contain a slew of brief examples. I'm not sure how to best keep them organized. They could turn into a cluttered mess. 

I saw on another sphinx-built web page where the link to the notebook was available to download it. If you see this, please make note so that we can implement it.

**Comment by raphaeltimbo** [comment]
I did some investigation regarding the links to download the notebooks.
Where do you want to put these links? I ask that because, if we want to put the link in the notebook itself like this: http://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_exp.html
I think there is no easy way to do that, since in this case the notebook is actually being transformed to a rst file before generating the html. This approach is different from the one that we are using with nbsphinx and there is actually an issue open for that https://github.com/spatialaudio/nbsphinx/issues/5

I think the easiest approach would be to put the links in some other place such as the home page using:
http://www.sphinx-doc.org/en/stable/markup/inline.html#referencing-downloadable-files

**Comment by josephcslater** [comment]
At this point, the second option is likely best. I'm sure I saw a cleaner looking solution, but I do not know if it was simple to implement.

**Comment by raphaeltimbo** [comment]
I think #51 is a good solution for the links issue.
Regarding the gallery, I was thinking about what you said of that becoming a mess and I think that a good thing would be to create a subpage for this part, in this way we could avoid several non related links in the main page keeping it more simple/organized.

**Comment by raphaeltimbo** [comment]
Did some work on the organization.
Please take a look at #53 and also at the updated web page.

**Comment by raphaeltimbo** [comment]
I am closing this one based on #53 .
If necessary we can reopen it latter.
