### ISSUE TITLE
"@" is a python operator?

### ISSUE THREAD

**Issue by comger** [vibrationtoolbox/vibration_toolbox#83]
like c=a@b; I can not find this operator in python2 and python3

**Comment by raphaeltimbo** [comment]
Yes, it is an operator introduced in python 3.5. It is used for matrix multiplication.
Here you can find more info: https://www.python.org/dev/peps/pep-0465/

**Comment by comger** [comment]
very nice !

**Comment by josephcslater** [comment]
It is specifically why the toolbox requires Python 3.5 or greater. It was initiated after the release of 3.5 and thus incorporate the much easier matrix multiplication. If there were a way (and we knew it) to make it backward compatible easily, we would.
