### ISSUE TITLE
I think setting up travis-ci is not quick and easy now 

### ISSUE THREAD

**Issue by ghost** [vibrationtoolbox/vibration_toolbox#86]
Hello Dr. Slater,

Steps to install in contributors mode may need to be changed or clarified. As following those steps lead to a note that says "GitHub services are being depreciated". For more details, please go thru the screenshot attached below:
![screenshot_2018-12-28 sainag2473 vibration_toolbox](https://user-images.githubusercontent.com/22245264/50500575-2434ce00-0a07-11e9-93c6-0dbd0f6d3e75.png)

Thanks,
Sainag.

**Comment by ghost** [comment]
Relevant Article on web: https://www.google.com/amp/s/hub.packtpub.com/github-plans-to-deprecate-github-services-and-move-to-webhooks-in-2019/amp/

**Comment by josephcslater** [comment]
OK. I have to look into it when I have time. Thanks.

**Comment by ghost** [comment]
Hello Dr. Slater,

Issue can be closed if it looks satisfactory.

Thanks,
Sainag.
