### ISSUE TITLE
Error: module 'vibration_toolbox' has no attribute 'time_plot'

### ISSUE THREAD

**Issue by bagustris** [vibrationtoolbox/vibration_toolbox#90]
I just want to try vibration_toolbox for the first time and it gives me an error when following the very first tutorial in the documentation [(SDOF)](http://vibrationtoolbox.github.io/vibration_toolbox/tutorial/sdof_notebook.html).

The first tutorial should work out the box, I think.

~~~
In [1]: import vibration_toolbox as vtb                                         

In [2]: vtb.time_plot()                                                         
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8990cfc61e28> in <module>
----> 1 vtb.time_plot()

AttributeError: module 'vibration_toolbox' has no attribute 'time_plot'

In [3]: vtb.__version__                                                         
Out[3]: '0.6.7'
~~~

**Comment by josephcslater** [comment]
Odd. It worked to actually create the docs. I will have to look at it when I get a chance. The next lines all seem to work, though.

**Comment by josephcslater** [comment]
Please update and confirm here that it works for you.

**Comment by bagustris** [comment]
Thanks, @josephcslater!

It works now. I am scanning the tutorial and will report/pr once I faced errors.
I planned to use this tool for tutoring vibration courses the year.

**Comment by josephcslater** [comment]
We had made the decision that those functions would only be used it Jupyter notebooks. So, we hide the ones without interaction. It's probably right, but I reverted the one. You may find others.  Assistance is certainly appreciated if you can make patches and pull requests. My current job doesn't provide time to work on such things, though I love to.

**Comment by bagustris** [comment]
Yes, I know from the error that the function is supposed to be run from Interactive mode, and I used IPython as shown above. So, not only Jupyter, but it should also work on IPython. I prefer to use IPython over Jupyter because it is faster and less complicated than Jupyter.

**Comment by josephcslater** [comment]
Please provide your feedback.  I wrote it after teaching such classes for decades multiple times per year, but never taught it since we put out the package.
